# Generated by Django 3.0.5 on 2020-10-09 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='school_name',
        ),
    ]
