# Generated by Django 3.1.2 on 2020-10-08 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('NURSERY', 'nursery'), ('LKG', 'LKG'), ('UKG', 'UKG'), ('CLASS1', 'class 1'), ('CLASS2', 'class 2'), ('CLASS3', 'class 3'), ('CLASS4', 'class 4'), ('CLASS5', 'class 5'), ('CLASS6', 'class 6'), ('CLASS7', 'class 7'), ('CLASS8', 'class 8'), ('CLASS9', 'class 9'), ('CLASS10', 'class 10')], max_length=255)),
            ],
        ),
    ]
