# Generated by Django 3.0 on 2020-09-28 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='school_name',
        ),
    ]
