# Generated by Django 3.0.5 on 2020-10-08 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('AD', 'admin'), ('T', 'teacher'), ('S', 'student')], default='S', max_length=20, verbose_name='user role'),
        ),
    ]
