# Generated by Django 3.0.5 on 2020-10-09 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20201008_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('T', 'teacher'), ('S', 'student')], default='S', max_length=20, verbose_name='user role'),
        ),
    ]
