# Generated by Django 3.0.5 on 2020-10-09 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20201009_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER', 'super'), ('TEACHER', 'teacher'), ('STUDENT', 'student')], default='S', max_length=20, verbose_name='user role'),
        ),
    ]
