# Generated by Django 3.1.1 on 2020-09-26 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='User',
            new_name='user',
        ),
    ]
