# Generated by Django 3.1.1 on 2020-10-05 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teacher', '0001_initial'),
        ('subjects', '0001_initial'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance_class_UKG',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('attendance_class', models.CharField(default='UKG', editable=False, max_length=200)),
                ('attendance_date', models.DateTimeField()),
                ('student', models.ManyToManyField(to='student.Student')),
                ('subject', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='subjects.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance_class_nursery',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('attendance_class', models.CharField(default='nursery', editable=False, max_length=200)),
                ('attendance_date', models.DateTimeField()),
                ('student', models.ManyToManyField(to='student.Student')),
                ('subject', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='subjects.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance_class_LKG',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('attendance_class', models.CharField(default='LKG', editable=False, max_length=200)),
                ('attendance_date', models.DateTimeField()),
                ('student', models.ManyToManyField(to='student.Student')),
                ('subject', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='subjects.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance_class_9',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('attendance_class', models.CharField(default='class 9', editable=False, max_length=200)),
                ('attendance_date', models.DateTimeField()),
                ('student', models.ManyToManyField(to='student.Student')),
                ('subject', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='subjects.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance_class_8',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('attendance_class', models.CharField(default='class 8', editable=False, max_length=200)),
                ('attendance_date', models.DateTimeField()),
                ('student', models.ManyToManyField(to='student.Student')),
                ('subject', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='subjects.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance_class_7',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('attendance_class', models.CharField(default='class 7', editable=False, max_length=200)),
                ('attendance_date', models.DateTimeField()),
                ('student', models.ManyToManyField(to='student.Student')),
                ('subject', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='subjects.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance_class_6',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('attendance_class', models.CharField(default='class 6', editable=False, max_length=200)),
                ('attendance_date', models.DateTimeField()),
                ('student', models.ManyToManyField(to='student.Student')),
                ('subject', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='subjects.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance_class_5',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('attendance_class', models.CharField(default='class 5', editable=False, max_length=200)),
                ('attendance_date', models.DateTimeField()),
                ('student', models.ManyToManyField(to='student.Student')),
                ('subject', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='subjects.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance_class_4',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('attendance_class', models.CharField(default='class 4', editable=False, max_length=200)),
                ('attendance_date', models.DateTimeField()),
                ('student', models.ManyToManyField(to='student.Student')),
                ('subject', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='subjects.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance_class_3',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('attendance_class', models.CharField(default='class 3', editable=False, max_length=200)),
                ('attendance_date', models.DateTimeField()),
                ('student', models.ManyToManyField(to='student.Student')),
                ('subject', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='subjects.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance_class_2',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('attendance_class', models.CharField(default='class 2', editable=False, max_length=200)),
                ('attendance_date', models.DateTimeField()),
                ('student', models.ManyToManyField(to='student.Student')),
                ('subject', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='subjects.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance_class_10',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('attendance_class', models.CharField(default='class 10', editable=False, max_length=200)),
                ('attendance_date', models.DateTimeField()),
                ('student', models.ManyToManyField(to='student.Student')),
                ('subject', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='subjects.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance_class_1',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('attendance_class', models.CharField(default='class 1', editable=False, max_length=200)),
                ('attendance_date', models.DateTimeField()),
                ('student', models.ManyToManyField(to='student.Student')),
                ('subject', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='subjects.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.teacher')),
            ],
        ),
    ]
