# Generated by Django 3.0.5 on 2020-10-13 12:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teacher', '0001_initial'),
        ('subjects', '0001_initial'),
        ('class_level', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendanceclass1',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('attendance_class', models.CharField(default='1', editable=False, max_length=200)),
                ('attendance_date', models.DateTimeField()),
                ('student', models.ManyToManyField(blank=True, to='class_level.Class_1_student')),
                ('subject', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='subjects.Subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Attendance_class_UKG',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('attendance_class', models.CharField(default='UKG', editable=False, max_length=200)),
                ('attendance_date', models.DateTimeField()),
                ('student', models.ManyToManyField(to='class_level.Class_ukg_student')),
                ('subject', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='subjects.Subject')),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Attendance_class_nursery',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('attendance_class', models.CharField(default='nursery', editable=False, max_length=200)),
                ('attendance_date', models.DateTimeField()),
                ('student', models.ManyToManyField(to='class_level.Class_nursery_student')),
                ('subject', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='subjects.Subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.Teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance_class_LKG',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('attendance_class', models.CharField(default='LKG', editable=False, max_length=200)),
                ('attendance_date', models.DateTimeField()),
                ('student', models.ManyToManyField(to='class_level.Class_lkg_student')),
                ('subject', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='subjects.Subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.Teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance_class_9',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('attendance_class', models.CharField(default='class 9', editable=False, max_length=200)),
                ('attendance_date', models.DateTimeField()),
                ('student', models.ManyToManyField(to='class_level.Class_9_student')),
                ('subject', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='subjects.Subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.Teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance_class_8',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('attendance_class', models.CharField(default='class 8', editable=False, max_length=200)),
                ('attendance_date', models.DateTimeField()),
                ('student', models.ManyToManyField(to='class_level.Class_8_student')),
                ('subject', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='subjects.Subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.Teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance_class_7',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('attendance_class', models.CharField(default='class 7', editable=False, max_length=200)),
                ('attendance_date', models.DateTimeField()),
                ('student', models.ManyToManyField(to='class_level.Class_7_student')),
                ('subject', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='subjects.Subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.Teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance_class_6',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('attendance_class', models.CharField(default='class 6', editable=False, max_length=200)),
                ('attendance_date', models.DateTimeField()),
                ('student', models.ManyToManyField(to='class_level.Class_6_student')),
                ('subject', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='subjects.Subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.Teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance_class_5',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('attendance_class', models.CharField(default='class 5', editable=False, max_length=200)),
                ('attendance_date', models.DateTimeField()),
                ('student', models.ManyToManyField(to='class_level.Class_5_student')),
                ('subject', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='subjects.Subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.Teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance_class_4',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('attendance_class', models.CharField(default='class 4', editable=False, max_length=200)),
                ('attendance_date', models.DateTimeField()),
                ('student', models.ManyToManyField(to='class_level.Class_4_student')),
                ('subject', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='subjects.Subject')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance_class_3',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('attendance_class', models.CharField(default='class 3', editable=False, max_length=200)),
                ('attendance_date', models.DateTimeField()),
                ('student', models.ManyToManyField(to='class_level.Class_3_student')),
                ('subject', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='subjects.Subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.Teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance_class_2',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('attendance_class', models.CharField(default='class 2', editable=False, max_length=200)),
                ('attendance_date', models.DateTimeField()),
                ('student', models.ManyToManyField(to='class_level.Class_2_student')),
                ('subject', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='subjects.Subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.Teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance_class_10',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('attendance_class', models.CharField(default='class 10', editable=False, max_length=200)),
                ('attendance_date', models.DateTimeField()),
                ('student', models.ManyToManyField(to='class_level.Class_10_student')),
                ('subject', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='subjects.Subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.Teacher')),
            ],
        ),
    ]
