# Generated by Django 3.1.2 on 2020-10-08 12:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('class_level', '0001_initial'),
        ('teacher', '0001_initial'),
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendanceclass1',
            name='student',
            field=models.ManyToManyField(blank=True, to='class_level.Class_1_student'),
        ),
        migrations.AddField(
            model_name='attendanceclass1',
            name='subject',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='subjects.subject'),
        ),
        migrations.AddField(
            model_name='attendanceclass1',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendance_class_ukg',
            name='student',
            field=models.ManyToManyField(to='class_level.Class_ukg_student'),
        ),
        migrations.AddField(
            model_name='attendance_class_ukg',
            name='subject',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='subjects.subject'),
        ),
        migrations.AddField(
            model_name='attendance_class_ukg',
            name='teacher',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendance_class_nursery',
            name='student',
            field=models.ManyToManyField(to='class_level.Class_nursery_student'),
        ),
        migrations.AddField(
            model_name='attendance_class_nursery',
            name='subject',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='subjects.subject'),
        ),
        migrations.AddField(
            model_name='attendance_class_nursery',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.teacher'),
        ),
        migrations.AddField(
            model_name='attendance_class_lkg',
            name='student',
            field=models.ManyToManyField(to='class_level.Class_lkg_student'),
        ),
        migrations.AddField(
            model_name='attendance_class_lkg',
            name='subject',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='subjects.subject'),
        ),
        migrations.AddField(
            model_name='attendance_class_lkg',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.teacher'),
        ),
        migrations.AddField(
            model_name='attendance_class_9',
            name='student',
            field=models.ManyToManyField(to='class_level.Class_9_student'),
        ),
        migrations.AddField(
            model_name='attendance_class_9',
            name='subject',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='subjects.subject'),
        ),
        migrations.AddField(
            model_name='attendance_class_9',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.teacher'),
        ),
        migrations.AddField(
            model_name='attendance_class_8',
            name='student',
            field=models.ManyToManyField(to='class_level.Class_8_student'),
        ),
        migrations.AddField(
            model_name='attendance_class_8',
            name='subject',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='subjects.subject'),
        ),
        migrations.AddField(
            model_name='attendance_class_8',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.teacher'),
        ),
        migrations.AddField(
            model_name='attendance_class_7',
            name='student',
            field=models.ManyToManyField(to='class_level.Class_7_student'),
        ),
        migrations.AddField(
            model_name='attendance_class_7',
            name='subject',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='subjects.subject'),
        ),
        migrations.AddField(
            model_name='attendance_class_7',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.teacher'),
        ),
        migrations.AddField(
            model_name='attendance_class_6',
            name='student',
            field=models.ManyToManyField(to='class_level.Class_6_student'),
        ),
        migrations.AddField(
            model_name='attendance_class_6',
            name='subject',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='subjects.subject'),
        ),
        migrations.AddField(
            model_name='attendance_class_6',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.teacher'),
        ),
        migrations.AddField(
            model_name='attendance_class_5',
            name='student',
            field=models.ManyToManyField(to='class_level.Class_5_student'),
        ),
        migrations.AddField(
            model_name='attendance_class_5',
            name='subject',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='subjects.subject'),
        ),
        migrations.AddField(
            model_name='attendance_class_5',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.teacher'),
        ),
        migrations.AddField(
            model_name='attendance_class_4',
            name='student',
            field=models.ManyToManyField(to='class_level.Class_4_student'),
        ),
        migrations.AddField(
            model_name='attendance_class_4',
            name='subject',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='subjects.subject'),
        ),
        migrations.AddField(
            model_name='attendance_class_3',
            name='student',
            field=models.ManyToManyField(to='class_level.Class_3_student'),
        ),
        migrations.AddField(
            model_name='attendance_class_3',
            name='subject',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='subjects.subject'),
        ),
        migrations.AddField(
            model_name='attendance_class_3',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.teacher'),
        ),
        migrations.AddField(
            model_name='attendance_class_2',
            name='student',
            field=models.ManyToManyField(to='class_level.Class_2_student'),
        ),
        migrations.AddField(
            model_name='attendance_class_2',
            name='subject',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='subjects.subject'),
        ),
        migrations.AddField(
            model_name='attendance_class_2',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.teacher'),
        ),
        migrations.AddField(
            model_name='attendance_class_10',
            name='student',
            field=models.ManyToManyField(to='class_level.Class_10_student'),
        ),
        migrations.AddField(
            model_name='attendance_class_10',
            name='subject',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='subjects.subject'),
        ),
        migrations.AddField(
            model_name='attendance_class_10',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.teacher'),
        ),
    ]
