# Generated by Django 3.0.5 on 2020-10-09 14:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('attendance', '0001_initial'),
        ('subjects', '0001_initial'),
        ('class_level', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendanceclass1',
            name='student',
            field=models.ManyToManyField(blank=True, to='class_level.Class_1_student'),
        ),
        migrations.AddField(
            model_name='attendanceclass1',
            name='subject',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='subjects.Subject'),
        ),
        migrations.AddField(
            model_name='attendanceclass1',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendance_class_ukg',
            name='student',
            field=models.ManyToManyField(to='class_level.Class_ukg_student'),
        ),
        migrations.AddField(
            model_name='attendance_class_ukg',
            name='subject',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='subjects.Subject'),
        ),
        migrations.AddField(
            model_name='attendance_class_ukg',
            name='teacher',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendance_class_nursery',
            name='student',
            field=models.ManyToManyField(to='class_level.Class_nursery_student'),
        ),
        migrations.AddField(
            model_name='attendance_class_nursery',
            name='subject',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='subjects.Subject'),
        ),
    ]
