# Generated by Django 3.0.5 on 2020-10-09 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0002_auto_20201009_1417'),
        ('teacher', '0001_initial'),
        ('subjects', '0001_initial'),
        ('class_level', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance_class_nursery',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.Teacher'),
        ),
        migrations.AddField(
            model_name='attendance_class_lkg',
            name='student',
            field=models.ManyToManyField(to='class_level.Class_lkg_student'),
        ),
        migrations.AddField(
            model_name='attendance_class_lkg',
            name='subject',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='subjects.Subject'),
        ),
        migrations.AddField(
            model_name='attendance_class_lkg',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.Teacher'),
        ),
        migrations.AddField(
            model_name='attendance_class_9',
            name='student',
            field=models.ManyToManyField(to='class_level.Class_9_student'),
        ),
        migrations.AddField(
            model_name='attendance_class_9',
            name='subject',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='subjects.Subject'),
        ),
        migrations.AddField(
            model_name='attendance_class_9',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.Teacher'),
        ),
        migrations.AddField(
            model_name='attendance_class_8',
            name='student',
            field=models.ManyToManyField(to='class_level.Class_8_student'),
        ),
        migrations.AddField(
            model_name='attendance_class_8',
            name='subject',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='subjects.Subject'),
        ),
        migrations.AddField(
            model_name='attendance_class_8',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.Teacher'),
        ),
        migrations.AddField(
            model_name='attendance_class_7',
            name='student',
            field=models.ManyToManyField(to='class_level.Class_7_student'),
        ),
        migrations.AddField(
            model_name='attendance_class_7',
            name='subject',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='subjects.Subject'),
        ),
        migrations.AddField(
            model_name='attendance_class_7',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.Teacher'),
        ),
        migrations.AddField(
            model_name='attendance_class_6',
            name='student',
            field=models.ManyToManyField(to='class_level.Class_6_student'),
        ),
        migrations.AddField(
            model_name='attendance_class_6',
            name='subject',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='subjects.Subject'),
        ),
        migrations.AddField(
            model_name='attendance_class_6',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.Teacher'),
        ),
        migrations.AddField(
            model_name='attendance_class_5',
            name='student',
            field=models.ManyToManyField(to='class_level.Class_5_student'),
        ),
        migrations.AddField(
            model_name='attendance_class_5',
            name='subject',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='subjects.Subject'),
        ),
        migrations.AddField(
            model_name='attendance_class_5',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.Teacher'),
        ),
        migrations.AddField(
            model_name='attendance_class_4',
            name='student',
            field=models.ManyToManyField(to='class_level.Class_4_student'),
        ),
        migrations.AddField(
            model_name='attendance_class_4',
            name='subject',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='subjects.Subject'),
        ),
        migrations.AddField(
            model_name='attendance_class_3',
            name='student',
            field=models.ManyToManyField(to='class_level.Class_3_student'),
        ),
        migrations.AddField(
            model_name='attendance_class_3',
            name='subject',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='subjects.Subject'),
        ),
        migrations.AddField(
            model_name='attendance_class_3',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.Teacher'),
        ),
        migrations.AddField(
            model_name='attendance_class_2',
            name='student',
            field=models.ManyToManyField(to='class_level.Class_2_student'),
        ),
        migrations.AddField(
            model_name='attendance_class_2',
            name='subject',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='subjects.Subject'),
        ),
        migrations.AddField(
            model_name='attendance_class_2',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.Teacher'),
        ),
        migrations.AddField(
            model_name='attendance_class_10',
            name='student',
            field=models.ManyToManyField(to='class_level.Class_10_student'),
        ),
        migrations.AddField(
            model_name='attendance_class_10',
            name='subject',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='subjects.Subject'),
        ),
        migrations.AddField(
            model_name='attendance_class_10',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.Teacher'),
        ),
    ]
