# Generated by Django 3.0.5 on 2020-10-14 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
        ('class_level', '0002_auto_20201014_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class_1_student',
            name='school_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school.School'),
        ),
    ]
