# Generated by Django 3.0.5 on 2020-10-14 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
        ('class_level', '0003_auto_20201014_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class_10_student',
            name='school_name',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='school.School'),
        ),
        migrations.AlterField(
            model_name='class_2_student',
            name='school_name',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='school.School'),
        ),
        migrations.AlterField(
            model_name='class_3_student',
            name='school_name',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='school.School'),
        ),
        migrations.AlterField(
            model_name='class_4_student',
            name='school_name',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='school.School'),
        ),
        migrations.AlterField(
            model_name='class_5_student',
            name='school_name',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='school.School'),
        ),
        migrations.AlterField(
            model_name='class_6_student',
            name='school_name',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='school.School'),
        ),
        migrations.AlterField(
            model_name='class_7_student',
            name='school_name',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='school.School'),
        ),
        migrations.AlterField(
            model_name='class_8_student',
            name='school_name',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='school.School'),
        ),
        migrations.AlterField(
            model_name='class_9_student',
            name='school_name',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='school.School'),
        ),
        migrations.AlterField(
            model_name='class_lkg_student',
            name='school_name',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='school.School'),
        ),
        migrations.AlterField(
            model_name='class_ukg_student',
            name='school_name',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='school.School'),
        ),
    ]
